In [1]:
import numpy as np
a=np.empty((3,3,3))#creates an random  array of order 3X3X3
print("The Array is-")
print(a)
print("The Shape of Array is-")
print(a.shape)

The Array is-
[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [1.69119330e-306 1.33511018e-306 1.33511969e-306]
  [6.23037996e-307 6.23053954e-307 9.34609790e-307]]

 [[8.45593934e-307 9.34600963e-307 1.86921143e-306]
  [6.23061763e-307 6.23060065e-307 8.45603441e-307]
  [9.79111267e-307 1.11260144e-306 1.60219035e-306]]

 [[8.34448533e-308 1.33508761e-307 1.33511562e-306]
  [8.90103560e-307 1.42410974e-306 1.00132228e-307]
  [1.33511969e-306 2.18568966e-312 2.29179042e-312]]]
The Shape of Array is-
(3, 3, 3)


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
b=np.zeros((4,4))
print("Initial Matrix-")
print(b)
for i in range(len(b)):
    for j in range(len(b)):
        if(i==j+1):
            b[i][j]=i
print("Final Matrix-")
print(b)

Initial Matrix-
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Final Matrix-
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
c=np.zeros((8,8))#creates a zeros matrix of specified order 
print("Initial Matrix-")
print(c)
for i in range(len(c)):
    for j in range(len(c)):
        if(j%2!=0):
            c[i][j]=255
print("Final Matrix-")
print(c)

Initial Matrix-
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Final Matrix-
[[  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]]


# 4. Normalize a 5x5 random matrix

In [5]:
d=np.random.randn(5,5)#creates a matrix of specified filled with random numbers
print("The random matrix is-")
print(d)
normal=np.linalg.norm(d)#computes the norm of the given matrix 
print("The norm value of random matrix is-")
print(normal)
e=np.divide(d,normal)#computes the normalized matrix
print("The normalized random mattrix is-")
print(e)

The random matrix is-
[[ 0.80072003 -2.34141241  0.74050849 -0.67883128  0.86983841]
 [ 1.23485862  0.50144093 -1.05403635  2.01512531  0.789562  ]
 [-0.51048205 -2.23317884 -0.91918667  1.39460946  0.42885486]
 [-1.11270234 -0.09076029  0.24202005 -1.23414966 -1.46926382]
 [ 1.39414988 -0.03305611  2.14101282  0.4764322   0.90298623]]
The norm value of random matrix is-
6.019955743925033
The normalized random mattrix is-
[[ 0.13301095 -0.3889418   0.12300896 -0.1127635   0.14449249]
 [ 0.20512753  0.08329645 -0.17509038  0.33474088  0.13115744]
 [-0.08479831 -0.37096267 -0.15268994  0.2316644   0.07123887]
 [-0.18483563 -0.01507657  0.04020296 -0.20500976 -0.24406555]
 [ 0.23158806 -0.00549109  0.35565258  0.07914214  0.14999881]]


# 5. How to find common values between two arrays?


In [6]:
f=np.array([1,2,3,4,5])
print("The 1st array is-")
print(f)
g=np.array([2,4,6,8,10])
print("The 2nd array is-")
print(g)
com_values=np.intersect1d(f,g)#computes common values in two input arrays
print("Common values between two arrays are-")
print(com_values)


The 1st array is-
[1 2 3 4 5]
The 2nd array is-
[ 2  4  6  8 10]
Common values between two arrays are-
[2 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
 yesterday =np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's Date: ",yesterday)
today= np.datetime64('today', 'D')
print("Today's Date: ",today)
tomorrow= np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's Date: ",tomorrow)

Yestraday's Date:  2020-07-27
Today's Date:  2020-07-28
Tomorrow's Date:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [8]:
h=np.array([1,2,3])
i=np.array([1,2,3])
comparison = h == i
equal_arrays = comparison.all()#compare two arrays and returns boolean expression
print("Output is True if two arrays are equal")
print("Output is False if two arrays are equal")
print("Output:",equal_arrays)

Output is True if two arrays are equal
Output is False if two arrays are equal
Output: True


In [9]:
h=np.array([1,2,3])
i=np.array([4,5,6])
comparison = h == i
equal_arrays = comparison.all()
print("Output is True if two arrays are equal")
print("Output is False if two arrays are equal")
print("Output:",equal_arrays)

Output is True if two arrays are equal
Output is False if two arrays are equal
Output: False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [10]:
vec=np.random.randn(10,1)#creates a random vector of given order
print("The random vector is-")
print(vec)
max_val=np.amax(vec)#computes the maximum value from a given vector
print("The maximum value in the vector is-")
print(max_val)
loc=np.where(vec==max_val)#find the index of the maximum value
vec[loc]=0
print("The new vector is-")
print(vec)

The random vector is-
[[-0.97405614]
 [ 0.41392074]
 [ 1.28491454]
 [-0.70790679]
 [-0.55164903]
 [-1.39869802]
 [-1.30545291]
 [ 3.63513915]
 [-0.83316454]
 [ 0.58702389]]
The maximum value in the vector is-
3.6351391468993683
The new vector is-
[[-0.97405614]
 [ 0.41392074]
 [ 1.28491454]
 [-0.70790679]
 [-0.55164903]
 [-1.39869802]
 [-1.30545291]
 [ 0.        ]
 [-0.83316454]
 [ 0.58702389]]


# 9. How to print all the values of an array?

In [11]:
l=np.random.randn(3,)#creates a random array of given order
print("The array is:")
print(l)
for i in range(len(l)):
    print("The element at index(",i,") is:",l[i])

The array is:
[1.16794979 0.4225643  0.94673857]
The element at index( 0 ) is: 1.1679497923003228
The element at index( 1 ) is: 0.422564299082986
The element at index( 2 ) is: 0.9467385663115679


In [12]:
l=np.random.randn(3,3)#creates a random array of given order
print("The array is:")
print(l)
for i in range(len(l)):
    for j in range(len(l)):
        print("The element at index(",i,",",j,")is:",l[i][j])

The array is:
[[ 0.02554538 -1.42684958  1.89210166]
 [ 1.3965061  -1.64846499 -0.62485114]
 [ 1.58973198 -0.07511576 -0.89777486]]
The element at index( 0 , 0 )is: 0.025545381237552924
The element at index( 0 , 1 )is: -1.4268495787244773
The element at index( 0 , 2 )is: 1.892101664706043
The element at index( 1 , 0 )is: 1.3965061041945892
The element at index( 1 , 1 )is: -1.6484649940457647
The element at index( 1 , 2 )is: -0.6248511440119224
The element at index( 2 , 0 )is: 1.5897319820735196
The element at index( 2 , 1 )is: -0.07511575841766024
The element at index( 2 , 2 )is: -0.8977748586202817


# 10.Subtract the mean of each row of a matrix

In [13]:
arr=np.random.randn(3,3)#creates a random matrix of given order
print("The matrix is-")
print(arr)
print("The mean value of each row is-")
arr1=np.mean(arr,axis=1)#computes the mean of each row
print(arr1)
arr2=arr-arr1
print("The matrix after the mean is subtracted-")
print(arr2)

The matrix is-
[[-1.89656167  0.14075871 -1.9373509 ]
 [-0.7853598  -0.17030867  0.62139727]
 [-0.65807611  1.01245342  0.93966634]]
The mean value of each row is-
[-1.23105129 -0.11142373  0.43134788]
The matrix after the mean is subtracted-
[[-0.66551038  0.25218244 -2.36869878]
 [ 0.44569149 -0.05888493  0.19004938]
 [ 0.57297517  1.12387715  0.50831846]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [14]:
Z = np.random.randn(10,1)#creates a random vector of given order
print("The original vector is:")
print(Z)
I=np.random.randint(0,len(Z),4)#generates 4 random integers in a specified range,used as index values
print("The Index values are:")
print(I)
print("Final vector after adding 1 to corresponding elements at the specified indices:")
np.add.at(Z,I,1)#Adds 1 to the elements in given vector (Z) at the specified index values(I)
print(Z)

The original vector is:
[[ 1.84649652]
 [ 0.53918354]
 [ 0.76265085]
 [ 0.68308069]
 [-0.15039523]
 [-0.47038158]
 [-0.29187792]
 [ 0.30813064]
 [ 0.93501066]
 [-0.99153658]]
The Index values are:
[7 1 4 8]
Final vector after adding 1 to corresponding elements at the specified indices:
[[ 1.84649652]
 [ 1.53918354]
 [ 0.76265085]
 [ 0.68308069]
 [ 0.84960477]
 [-0.47038158]
 [-0.29187792]
 [ 1.30813064]
 [ 1.93501066]
 [-0.99153658]]
